# Generated by Django 4.1.7 on 2023-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discounts_newsletter',
            field=models.BooleanField(default=False, verbose_name='Allow receiving a weekly newsletter with discounts'),
        ),
    ]
