# Generated by Django 4.1.7 on 2023-06-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_discounts_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_chat_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
