version: '3.9'

services:
  redis:
    image: redis
    container_name: broker_redis
    volumes:
      - /redis_dump/:/var/lib/redis/
      - /redis_data/:/data/
    ports:
      - '127.0.0.1:63791:6379'
