# Generated by Django 4.1.7 on 2023-04-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
