# Generated by Django 4.1.7 on 2023-04-09 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_basket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
