# Generated by Django 4.1.7 on 2023-04-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_basket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.CheckConstraint(check=models.Q(('count__gt', 0)), name='count'),
        ),
    ]
