# Generated by Django 4.1.7 on 2023-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_basket_count_basket_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basket',
            name='count',
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.CheckConstraint(check=models.Q(('count__gte', 0)), name='count'),
        ),
    ]
